### 获取请求 demo
GET http://localhost:8080/demo/create-demo

### json 请求示例
POST http://localhost:8080/demo/json-body
timestamp:1772501688016
nonce:3b93446bec0647c4a314820f571af5bf
sign:c9d798e9abd1a6924e4f49f514f3b074
Content-Type: application/json

{
  "name": "nzxy",
  "age": 18
}

### json 请求示例（部分参数参与签名验证）
POST http://localhost:8080/demo/json-body-some-params
timestamp:1772501688016
nonce:3b93446bec06q47c4a3w14820f571af5bf
sign:c9d798e9abd1a6924e4f49f514f3b074
Content-Type: application/json

{
  "name": "nzxy",
  "age": 18,
  "otherParam": "xwqqxx"
}

### form 请求示例
POST http://localhost:8080/demo/form-body
timestamp:1772501688016
nonce:3b93446bec0647c4a314820f571af5bf
sign:c9d798e9abd1a6924e4f49f514f3b074
Content-Type: application/x-www-form-urlencoded

name=nzxy&age=18

### query 请求示例
POST http://localhost:8080/demo/form-body?name=nzxy&age=18
timestamp:1772501688016
nonce:3b93446bec0647c4a314820f571af5bf
sign:c9d798e9abd1a6924e4f49f514f3b074
Content-Type: application/x-www-form-urlencoded